const Action = {
  UI_REVIVE_REDUCER: "UI_REVIVE_REDUCER",
  UI_POKEMON_DETAILS_WIDTH: "UI_POKEMON_DETAILS_WIDTH",
  UI_POKEMON_LIST_HIGHLIGHT: "UI_POKEMON_LIST_HIGHLIGHT",

  POKEMON_MAIN_LIST_REVIVE_REDUCER: "POKEMON_MAIN_LIST_REVIVE_REDUCER",
  POKEMON_MAIN_LIST_ADD: "POKEMON_MAIN_LIST_ADD",
  POKEMON_MAIN_LIST_CLEAR: "POKEMON_MAIN_LIST_CLEAR",
  POKEMON_MAIN_LIST_PAGE: "POKEMON_MAIN_LIST_PAGE",
  POKEMON_MAIN_LIST_COUNT: "POKEMON_MAIN_LIST_COUNT",
};

const UI = {
  POKEMON_DETAILS_WIDTH: "pokemonDetailsWidth",
  POKEMON_LIST_HIGHLIGHT: "pokemonListHighlight",
};

const PokemonMainList = {
  POKEMONS: "pokemons",
  COUNT: "count",
  PAGE: "page",
};

export { Action, UI, PokemonMainList };
