const Responsive = {
  MOBILE_BREAKPOINT: 1215,
};

const Store = {
  UI_POKEMON_DETAILS_WIDTH: "UI_POKEMON_DETAILS_WIDTH",

  POKEMON_MAIN_LIST_ADD: "POKEMON_MAIN_LIST_ADD",
  POKEMON_MAIN_LIST_CLEAR: "POKEMON_MAIN_LIST_CLEAR",
  POKEMON_MAIN_LIST_PAGE: "POKEMON_MAIN_LIST_PAGE",
  POKEMON_MAIN_LIST_COUNT: "POKEMON_MAIN_LIST_COUNT",
};

const Pagination = {
  TYPE_ELEMENT_FIRST_LAST: "PAGINATION_ELEMENT_FIRST_LAST",
  TYPE_ELEMENT_ELLIPSIS: "PAGINATION_ELEMENT_ELLIPSIS",
  TYPE_ELEMENT_DEFAULT: "PAGINATION_ELEMENT_DEFAULT",
  TYPE_ELEMENT_NONE: "PAGINATION_ELEMENT_NONE",
};

const Handler = {
  DIRECTION_TOP: "HANDLER_DIRECTION_TOP",
  DIRECTION_BOTTOM: "HANDLER_DIRECTION_BOTTOM",
  DIRECTION_LEFT: "HANDLER_DIRECTION_LEFT",
  DIRECTION_RIGHT: "HANDLER_DIRECTION_RIGHT",
};

export { Responsive, Store, Pagination, Handler };
