const Store = {
  POKEMON_MAIN_LIST_ADD: "POKEMON_MAIN_LIST_ADD",
  POKEMON_MAIN_LIST_CLEAR: "POKEMON_MAIN_LIST_CLEAR",
  POKEMON_MAIN_LIST_PAGE: "POKEMON_MAIN_LIST_PAGE",
  POKEMON_MAIN_LIST_COUNT: "POKEMON_MAIN_LIST_COUNT",
};

const Pagination = {
  TYPE_ELEMENT_FIRST_LAST: "PAGINATION_ELEMENT_FIRST_LAST",
  TYPE_ELEMENT_ELLIPSIS: "PAGINATION_ELEMENT_ELLIPSIS",
  TYPE_ELEMENT_DEFAULT: "PAGINATION_ELEMENT_DEFAULT",
  TYPE_ELEMENT_NONE: "PAGINATION_ELEMENT_NONE",
};

export { Store, Pagination };
